<li>
        <div class="main_pic_shadow"> <a href="[field:arcurl/]" target="_blank">
          <div class="pc-eye-bg innerDiv" data-img = 'true'> <img src="[field:litpic/]" class="pc-image targetImg"> </div>
          </a>
          <div class="main_prm">
            <div class="main_prm_left">
              <p><a href="[field:arcurl/]" target="_blank">[field:title/]</a></p>
              <p>价格：<span>[field:jiage/]</span> 　编号：[field:bianhao/]</p>
              <p>更新时间：[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</p>
            </div>
            <a href="[field:yanshi/]" title="演示地址" class="to_example" target="_blank">演示</a> </div>
          <div class="pcwp"> <a href="[field:arcurl/]"><img src="[field:pic2/]"></a> </div>
        </div>
      </li>