<div class="blog-item">
          <div class="thum"> <img src="images/1-1F4161F132C4.gif"> </div>
          <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
          <div class="info"> <span>类目:<a href="[field:typeurl/]" style="text-decoration:none; color:#000">[field:typename/]</a></span> <span class="time">[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</span> </div>
          <div class="j_content content ">[field:description function='cn_substr(@me,250)'/]...</div>
          <div class="readmore"><a href="[field:arcurl/]">[阅读全文]</a></div>
        </div>