
<field:bianhao itemname="模版编号" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:bianhao>

<field:yanshi itemname="演示地址" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:yanshi>

<field:jiage itemname="模版价格" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jiage>

<field:pic1 itemname="电脑版截图" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic1>
