<?php
$z[0]=Array("field","(@me==\"\")? @me=\" class='nav-link-cur'\":@me=\"\";",258,354);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[1]=Array("channel","\r\n      <li class='nav-item'><a class='nav-link' href='[field:typelink/]' >[field:typename/]</a></li>\r\n      ",378,634);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[1][4]['currentstyle']="<li class='nav-item'><a href='~typelink~' class='nav-link nav-link-cur'>~typename~</a></li>";
$z[2]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        ",827,953);
$z[2][4]=array();
$z[2][4]['type']="top";
$z[2][4]['row']="10";

?>